#!/bin/sh
here="$(realpath "$(dirname "$0")")"
if [ ! -e "$here/build/bin/tomo" ]; then
    echo "Tomo hasn't been compiled yet! Run \`make\` to compile it!"
    exit 1;
fi

PATH="$here/build/bin:$PATH" \
LD_LIBRARY_PATH="$here/build/lib" \
LIBRARY_PATH="$here/build/lib" \
C_INCLUDE_PATH="$here/build/include" \
tomo "$@"
