#!/bin/sh
version=$(awk '/^## / {print $2; exit}' CHANGES.md)
platform="$(uname -m)-linux"
if ! [ -e "./build/$platform/tomo@$version/bin/tomo" ]; then
    make -j
fi
exec "./build/$platform/tomo@$version/bin/tomo" "$@"
