// The tomo CLI's subcommands, one per src/cmd/*.c file

#pragma once

#include "../stdlib/cli.h"
#include "../stdlib/datatypes.h"

extern cli_command_t run_command, build_command, transpile_command, parse_command, fmt_command, package_command,
    install_command, uninstall_command, uninstall_self_command, vendor_command, info_command, version_command,
    eval_command, test_command;

// The tomo CLI itself (defined in tomo.c); its usage/help text is
// autogenerated during dispatch:
extern cli_spec_t tomo_cli;

// Compile the .tm file at `path` and exec it (shared by `tomo run` and
// `tomo eval`); defined in run.c:
int compile_and_exec(Path_t path, List_t extra_args);
