// Command line argument parsing

#pragma once

#include <stdbool.h>

#include "datatypes.h"
#include "types.h"

typedef struct {
    const char *name;
    void *dest;
    const TypeInfo_t *type;
    char short_flag;
    bool required, populated;
    // Optional presentation info for autogenerated usage/help text:
    const char *description; // one-line description of the flag
    const char *metavar;     // display name for the value (default: derived from the type)
    bool positional;         // display as a positional argument instead of a flag
} cli_arg_t;

// The help/version/usage text for one argument-parsing pass, along with which
// short flags (if any) the automatic --help and --version flags claim:
typedef struct {
    Text_t usage, help;
    const char *version;     // NULL: no automatic --version flag
    char help_short;         // short alias for --help ('h'), or 0 for none
    char version_short;      // short alias for --version ('v'), or 0 for none
    bool strict_positionals; // only fill positional values into .positional spec entries
                             // (subcommand parsing); otherwise any unpopulated entry can
                             // be filled positionally (generated programs' main())
} cli_help_info_t;

void tomo_parse_args(int argc, char *argv[], Text_t usage, Text_t help, const char *version, int spec_len,
                     cli_arg_t spec[spec_len]);
void tomo_parse_arg_list(List_t args, cli_help_info_t info, int spec_len, cli_arg_t spec[spec_len]);

// One subcommand in a git-style CLI (`tomo run ...`, `tomo build ...`):
typedef struct cli_command_s cli_command_t;
struct cli_command_s {
    const char *name;        // "run", "build", ...
    const char *summary;     // one-liner shown in the top-level help listing
    const char *description; // optional prose paragraph for the command's help
    // Usage/help shown for `<prog> <cmd> --help` and parse errors; leave
    // empty to have them autogenerated from the spec at startup:
    Text_t usage, help;
    int spec_len;
    cli_arg_t *spec; // command-specific flags and positionals
    // extra_args is the raw argv tail after the first bare "--", untouched:
    int (*handler)(cli_command_t *self, List_t extra_args);
};

// A whole subcommand-style CLI. Global flags are valid anywhere on the
// command line (they are popped before command dispatch), so global and
// command-specific flag names/short flags must be disjoint.
typedef struct {
    const char *name;        // the program name, e.g. "tomo"
    const char *summary;     // one-liner shown at the top of the help
    const char *description; // optional prose paragraph for the top-level help
    // Leave empty to have these autogenerated from the commands + global spec:
    Text_t usage, help;
    const char *version; // NULL: no automatic --version flag (long-only when set)
    int global_len;
    cli_arg_t *global_spec; // flags valid anywhere on the command line
    int num_commands;
    cli_command_t **commands;
    // Runs after global flags are popped, before command dispatch:
    void (*after_globals)(void);
    // Called when argv[1] is not a command name (bare files, no args, etc.):
    int (*fallback)(List_t args, List_t extra_args);
} cli_spec_t;

int tomo_dispatch_command(int argc, char *argv[], cli_spec_t *cli);

bool pop_cli_flag(List_t *args, char short_flag, const char *flag, void *dest, const TypeInfo_t *type);
bool pop_cli_positional(List_t *args, const char *flag, void *dest, const TypeInfo_t *type, bool allow_dashes);
