#pragma once

#include "datatypes.h"
#include "types.h"

// An enum used for iterating over lines in a file
// Most of the code here was generated by compiling:
//    enum NextLine(Done, Next(line:Text))

typedef struct NextLine_s NextLine_t;
typedef struct NextLine$Done_s NextLine$Done_t;
#pragma GCC diagnostic ignored "-Wpedantic"
struct NextLine$Done_s {
};
typedef struct NextLine$Next_s NextLine$Next_t;
struct NextLine$Next_s {
    Text_t $line;
};
struct NextLine_s {
    enum { NextLine$tag$Done = 0, NextLine$tag$Next = 1 } tag;
    union {
        NextLine$Done_t $Done;
        NextLine$Next_t $Next;
    };
};
extern const TypeInfo NextLine;
extern const TypeInfo NextLine$Done;
extern const TypeInfo NextLine$Next;
NextLine_t NextLine$tagged$Next(Text_t $line);

// vim: ts=4 sw=0 et cino=L2,l1,(0,W4,m1,\:0
