// This file defines how to compile CLI argument parsing

#pragma once

#include "../ast.h"
#include "../environment.h"
#include "../stdlib/datatypes.h"
#include "../types.h"

// A roff comment prepended to every Tomo-generated man page. `tomo uninstall`
// scans for it so it only ever removes man pages Tomo itself produced (see
// is_tomo_manpage()), never a hand-written page that happens to share a name.
#define TOMO_MANPAGE_MARKER ".\\\" Generated by Tomo"

Text_t compile_cli_arg_call(env_t *env, ast_t *ast, Text_t fn_name, type_t *fn_type);
Text_t compile_manpage(Text_t program, ast_t *ast, arg_t *args);
