'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.exp2 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float64.exp2 \- base-2 exponentiation
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.exp2\ :\ func(x:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes $2^x$ for a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float64	The exponent. 
.TE
.SH RETURN
The value of $2^x$.

.SH EXAMPLES
.EX
assert (3.0).exp2() == 8
.EE
.SH SEE ALSO
.BR Tomo-Float64 (3)
