'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.ceil 3 2025-04-30 "Tomo man-pages"
.SH NAME
Num.ceil \- ceiling function
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.ceil\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Rounds a number up to the nearest integer.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number to be rounded up. 	-
.TE
.SH RETURN
The smallest integer greater than or equal to `x`.

.SH EXAMPLES
.EX
>> (3.2).ceil()
= 4
.EE
