'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH USE_COLOR 3 2025-04-27 "Tomo man-pages"
.SH NAME
USE_COLOR \- whether to use colors
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI USE_COLOR\ :\ Bool
.fi
.SH DESCRIPTION
Whether or not the console prefers ANSI color escape sequences in the output.


