'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Set.add_all 3 2025-04-21T14:44:34.263371 "Tomo man-pages"
.SH NAME
Set.add_all \- add items to a set
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Set.add_all\ :\ func(set:\ @|T|,\ items:\ [T]\ ->\ Void)
.fi
.SH DESCRIPTION
Adds multiple items to the set.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
set	@|T|	The mutable reference to the set. 	-
items	[T]	The list of items to add to the set. 	-
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
>> nums.add_all([1, 2, 3])
.EE
