'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH sleep 3 2025-04-19T14:48:15.710068 "Tomo man-pages"
.SH NAME
sleep \- Pause execution for a given number of seconds.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI sleep\ :\ func(seconds:\ Num\ ->\ Void)
.fi

.SH DESCRIPTION
Pause execution for a given number of seconds.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
seconds	Num	How many seconds to sleep for. 	-
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
sleep(1.5)
.EE
