'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.y1 3 2025-04-21T14:44:34.261398 "Tomo man-pages"
.SH NAME
Num.y1 \- Bessel function
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.y1\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the Bessel function of the second kind of order 1.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the Bessel function is to be calculated. 	-
.TE
.SH RETURN
The Bessel function of the second kind of order 1 of `x`.

.SH EXAMPLES
.EX
>> (1.0).y1()
= 0.4401
.EE
