'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.is_file 3 2025-04-27 "Tomo man-pages"
.SH NAME
Path.is_file \- check if a path is a file
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.is_file\ :\ func(path:\ Path,\ follow_symlinks\ =\ yes\ ->\ Bool)
.fi
.SH DESCRIPTION
Checks if the path represents a file. Optionally follows symbolic links.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path to check. 	-
follow_symlinks		Whether to follow symbolic links. 	yes
.TE
.SH RETURN
`True` if the path is a file, `False` otherwise.

.SH EXAMPLES
.EX
>> (./file.txt).is_file()
= yes

>> (./directory/).is_file()
= no
.EE
