'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.acosh 3 2025-04-21T14:54:02.045703 "Tomo man-pages"
.SH NAME
Num.acosh \- arc hyperbolic cosine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.acosh\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the inverse hyperbolic cosine of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the inverse hyperbolic cosine is to be calculated. 	-
.TE
.SH RETURN
The inverse hyperbolic cosine of `x`.

.SH EXAMPLES
.EX
>> (1.0).acosh()
= 0
.EE
