'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.TAU 3 2026-08-27 "Tomo man-pages"
.SH NAME
Num.TAU \- the constant tau
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.TAU\ :\ Num
.fi
.SH DESCRIPTION
Two times pi, held exactly.


.SH EXAMPLES
.EX
assert Num.TAU == 2 * Num.PI
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
