'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Table.remove 3 2025-11-09 "Tomo man-pages"
.SH NAME
Table.remove \- remove a table entry
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Table.remove\ :\ func(t:\ {K:V},\ key:\ K\ ->\ Void)
.fi
.SH DESCRIPTION
Removes the key-value pair associated with a specified key.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
t	{K:V}	The reference to the table. 	-
key	K	The key of the key-value pair to remove. 	-
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
t := {"A": 1, "B": 2}
t.remove("A")
assert t == {"B": 2}
.EE
