'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.copysign 3 2025-04-19T14:52:07.135004 "Tomo man-pages"
.SH NAME
Num.copysign \- Copies the sign of one number to another.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.copysign\ :\ func(x:\ Num,\ y:\ Num\ ->\ Num)
.fi

.SH DESCRIPTION
Copies the sign of one number to another.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number whose magnitude will be copied. 	-
y	Num	The number whose sign will be copied. 	-
.TE
.SH RETURN
A number with the magnitude of `x` and the sign of `y`.

.SH EXAMPLES
.EX
>> (3.0).copysign(-1)
= -3
.EE
