'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH sleep 3 2025-11-09 "Tomo man-pages"
.SH NAME
sleep \- wait for an interval
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI sleep\ :\ func(seconds:\ Float64\ ->\ Void)
.fi
.SH DESCRIPTION
Pause execution for a given number of seconds.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
seconds	Float64	How many seconds to sleep for. 	-
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
sleep(1.5)
.EE
