'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Set.remove_all 3 2025-04-21T14:44:34.263618 "Tomo man-pages"
.SH NAME
Set.remove_all \- remove items from a set
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Set.remove_all\ :\ func(set:\ @|T|,\ items:\ [T]\ ->\ Void)
.fi
.SH DESCRIPTION
Removes multiple items from the set.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
set	@|T|	The mutable reference to the set. 	-
items	[T]	The list of items to remove from the set. 	-
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
>> nums.remove_all([1, 2, 3])
.EE
