'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.2_SQRTPI 3 2025-04-19T14:48:15.714076 "Tomo man-pages"
.SH NAME
Num.2_SQRTPI \- The constant $2 \times \sqrt{\pi}$.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.2_SQRTPI\ :\ Num
.fi

.SH DESCRIPTION
The constant $2 \times \sqrt{\pi}$.

