'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Text.replace 3 2025-04-21T14:44:34.264751 "Tomo man-pages"
.SH NAME
Text.replace \- replace a substring
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Text.replace\ :\ func(text:\ Text,\ target:\ Text,\ replacement:\ Text\ ->\ Text)
.fi
.SH DESCRIPTION
Replaces occurrences of a target text with a replacement text.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
text	Text	The text in which to perform replacements. 	-
target	Text	The target text to be replaced. 	-
replacement	Text	The text to replace the target with. 	-
.TE
.SH RETURN
The text with occurrences of the target replaced.

.SH EXAMPLES
.EX
>> "Hello world".replace("world", "there")
= "Hello there"
.EE
