'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Set.add 3 2025-04-21T14:44:34.263338 "Tomo man-pages"
.SH NAME
Set.add \- add item to a set
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Set.add\ :\ func(set:\ |T|,\ item:\ T\ ->\ Void)
.fi
.SH DESCRIPTION
Adds an item to the set.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
set	|T|	The mutable reference to the set. 	-
item	T	The item to add to the set. 	-
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
>> nums.add(42)
.EE
