'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float.acosh 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float.acosh \- arc hyperbolic cosine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float.acosh\ :\ func(x:\ Float\ ->\ Float)
.fi
.SH DESCRIPTION
Computes the inverse hyperbolic cosine of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float	The number for which the inverse hyperbolic cosine is to be calculated. 
.TE
.SH RETURN
The inverse hyperbolic cosine of `x`.

.SH EXAMPLES
.EX
assert (1.0).acosh() == 0
.EE
.SH SEE ALSO
.BR Tomo-Float (3)
