'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.log1p 3 2025-11-29 "Tomo man-pages"
.SH NAME
Num.log1p \- logarithm of 1 plus x
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.log1p\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes $\log(1 + x)$ for a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which $\log(1 + x)$ is to be calculated. 	-
.TE
.SH RETURN
The value of $\log(1 + x)$.

.SH EXAMPLES
.EX
assert (1.0).log1p() == 0.6931
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
