'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.base_name 3 2025-05-17 "Tomo man-pages"
.SH NAME
Path.base_name \- base name of a file
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.base_name\ :\ func(path:\ Path\ ->\ Text)
.fi
.SH DESCRIPTION
Returns the base name of the file or directory at the specified path.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path of the file or directory. 	-
.TE
.SH RETURN
The base name of the file or directory.

.SH EXAMPLES
.EX
>> (./path/to/file.txt).base_name()
= "file.txt"
.EE
