'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Text.split_any 3 2025-04-19T14:52:07.140522 "Tomo man-pages"
.SH NAME
Text.split_any \- Splits the text into a list of substrings at one or more occurrences of a set of delimiter characters (grapheme clusters).

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Text.split_any\ :\ func(text:\ Text,\ delimiters:\ Text\ =\ "\ $\[rs]t\[rs]r\[rs]n"\ ->\ [Text])
.fi

.SH DESCRIPTION
Splits the text into a list of substrings at one or more occurrences of a set of delimiter characters (grapheme clusters).


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
text	Text	The text to be split. 	-
delimiters	Text	A text containing delimiters to use for splitting the text. 	"\ $\[rs]t\[rs]r\[rs]n"
.TE
.SH RETURN
A list of subtexts resulting from the split.

.SH NOTES
Splitting will occur on every place where one or more of the grapheme clusters in `delimiters` occurs.
To split based on an exact delimiter, use Text.split().

.SH EXAMPLES
.EX
>> "one, two,,three".split_any(", ")
= ["one", "two", "three"]
.EE
