'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.files 3 2025-04-19T14:52:07.137843 "Tomo man-pages"
.SH NAME
Path.files \- Returns a list of files within the directory at the specified path. Optionally includes hidden files.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.files\ :\ func(path:\ Path,\ include_hidden:\ Bool\ =\ no\ ->\ [Path])
.fi

.SH DESCRIPTION
Returns a list of files within the directory at the specified path. Optionally includes hidden files.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path of the directory. 	-
include_hidden	Bool	Whether to include hidden files. 	no
.TE
.SH RETURN
A list of file paths.

.SH EXAMPLES
.EX
>> (./directory).files(include_hidden=yes)
= [(./directory/file1.txt), (./directory/file2.txt)]
.EE
