'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.mix 3 2025-04-19T14:30:40.363337 "Tomo man-pages"
.SH NAME
Num.mix \- Interpolates between two numbers based on a given amount.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI "Num.mix : func(amount: Num, x: Num, y: Num -> Num)"
.fi

.SH DESCRIPTION
Interpolates between two numbers based on a given amount.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
amount	Num	The interpolation factor (between `0` and `1`). 	-
x	Num	The starting number. 	-
y	Num	The ending number. 	-
.TE
.SH RETURN
The interpolated number between `x` and `y` based on `amount`.

.SH EXAMPLES
.EX
>> (0.5).mix(10, 20)
= 15
>> (0.25).mix(10, 20)
= 12.5
.EE
