'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float.isinf 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float.isinf \- check for infinite number
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float.isinf\ :\ func(n:\ Float\ ->\ Bool)
.fi
.SH DESCRIPTION
Checks if a number is infinite.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
n	Float	The number to be checked. 
.TE
.SH RETURN
`yes` if `n` is infinite, `no` otherwise.

.SH EXAMPLES
.EX
assert Float.INF.isinf() == yes
assert (1.0).isinf() == no
.EE
.SH SEE ALSO
.BR Tomo-Float (3)
