'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.cos 3 2025-11-29 "Tomo man-pages"
.SH NAME
Num.cos \- cosine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.cos\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the cosine of a number (angle in radians).


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The angle in radians. 	-
.TE
.SH RETURN
The cosine of `x`.

.SH EXAMPLES
.EX
assert (0.0).cos() == 1
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
