'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.significand 3 2025-04-19T14:48:15.713625 "Tomo man-pages"
.SH NAME
Num.significand \- Extracts the significand (or mantissa) of a number.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.significand\ :\ func(x:\ Num\ ->\ Num)
.fi

.SH DESCRIPTION
Extracts the significand (or mantissa) of a number.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number from which to extract the significand. 	-
.TE
.SH RETURN
The significand of `x`.

.SH EXAMPLES
.EX
>> (1234.567).significand()
= 0.1234567
.EE
