'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.read 3 2025-11-29 "Tomo man-pages"
.SH NAME
Path.read \- read file contents
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.read\ :\ func(path:\ Path\ ->\ Text?)
.fi
.SH DESCRIPTION
Reads the contents of the file at the specified path or none if the file could not be read.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path of the file to read. 	-
.TE
.SH RETURN
The contents of the file. If the file could not be read, none will be returned. If the file can be read, but is not valid UTF8 data, an error will be raised.

.SH EXAMPLES
.EX
assert (./hello.txt).read() == "Hello"
assert (./nosuchfile.xxx).read() == none
.EE
.SH SEE ALSO
.BR Tomo-Path (3)
