'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH List.random 3 2025-04-30 "Tomo man-pages"
.SH NAME
List.random \- pick a random element
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI List.random\ :\ func(list:\ [T],\ random:\ func(min,max:Int64->Int64)?\ =\ none\ ->\ T)
.fi
.SH DESCRIPTION
Selects a random element from the list.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
list	[T]	The list from which to select a random element. 	-
random	func(min,max:Int64->Int64)?	If provided, this function will be used to get a random index in the list. Returned values must be between `min` and `max` (inclusive). (Used for deterministic pseudorandom number generation) 	none
.TE
.SH RETURN
A random element from the list.

.SH EXAMPLES
.EX
>> [10, 20, 30].random()
= 20
.EE
