'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Int.onward 3 2025-11-29 "Tomo man-pages"
.SH NAME
Int.onward \- iterate from a number onward
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Int.onward\ :\ func(first:\ Int,\ step:\ Int\ =\ 1\ ->\ Text)
.fi
.SH DESCRIPTION
Return an iterator that counts infinitely from the starting integer (with an optional step size).


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
first	Int	The starting integer. 	-
step	Int	The increment step size. 	1
.TE
.SH RETURN
An iterator function that counts onward from the starting integer.

.SH EXAMPLES
.EX
nums : &[Int] = &[]
for i in (5).onward()
nums.insert(i)
stop if i == 10
assert nums[] == [5, 6, 7, 8, 9, 10]
.EE
.SH SEE ALSO
.BR Tomo-Int (3)
