'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.logb 3 2025-04-21T14:54:02.046740 "Tomo man-pages"
.SH NAME
Num.logb \- exponent of a floating point value
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.logb\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the binary exponent (base-2 logarithm) of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the binary exponent is to be calculated. 	-
.TE
.SH RETURN
The binary exponent of `x`.

.SH EXAMPLES
.EX
>> (8.0).logb()
= 3
.EE
