'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float.acos 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float.acos \- arc cosine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float.acos\ :\ func(x:\ Float\ ->\ Float)
.fi
.SH DESCRIPTION
Computes the arc cosine of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float	The number for which the arc cosine is to be calculated. 
.TE
.SH RETURN
The arc cosine of `x` in radians.

.SH EXAMPLES
.EX
assert (0.0).acos() == 1.5708
.EE
.SH SEE ALSO
.BR Tomo-Float (3)
