'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Bool.parse 3 2025-11-09 "Tomo man-pages"
.SH NAME
Bool.parse \- parse into boolean
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Bool.parse\ :\ func(text:\ Text,\ remainder:\ &Text?\ =\ none\ ->\ Bool?)
.fi
.SH DESCRIPTION
Converts a text representation of a boolean value into a boolean. Acceptable boolean values are case-insensitive variations of `yes`/`no`, `y`/`n`, `true`/`false`, `on`/`off`.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
text	Text	The string containing the boolean value. 	-
remainder	&Text?	If non-none, this argument will be set to the remainder of the text after the matching part. If none, parsing will only succeed if the entire text matches. 	none
.TE
.SH RETURN
`yes` if the string matches a recognized truthy boolean value; otherwise return `no`.

.SH EXAMPLES
.EX
assert Bool.parse("yes") == yes
assert Bool.parse("no") == no
assert Bool.parse("???") == none

assert Bool.parse("yesJUNK") == none
remainder : Text
assert Bool.parse("yesJUNK", &remainder) == yes
assert remainder == "JUNK"
.EE
