'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH List.shuffled 3 2025-04-21 "Tomo man-pages"
.SH NAME
List.shuffled \- return a shuffled list
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI List.shuffled\ :\ func(list:\ [T],\ random:\ func(min,max:Int64->Int64)?\ =\ none\ ->\ [T])
.fi
.SH DESCRIPTION
Creates a new list with elements shuffled.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
list	[T]	The list to be shuffled. 	-
random	func(min,max:Int64->Int64)?	If provided, this function will be used to get a random index in the list. Returned values must be between `min` and `max` (inclusive). (Used for deterministic pseudorandom number generation) 	none
.TE
.SH RETURN
A new list with shuffled elements.

.SH EXAMPLES
.EX
>> [10, 20, 30, 40].shuffled()
= [40, 10, 30, 20]
.EE
