'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.tanh 3 2025-09-21 "Tomo man-pages"
.SH NAME
Num.tanh \- hyperbolic tangent
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.tanh\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the hyperbolic tangent of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the hyperbolic tangent is to be calculated. 	-
.TE
.SH RETURN
The hyperbolic tangent of `x`.

.SH EXAMPLES
.EX
assert (0.0).tanh() == 0
.EE
