'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.create_directory 3 2025-04-19T14:48:15.714942 "Tomo man-pages"
.SH NAME
Path.create_directory \- Creates a new directory at the specified path with the given permissions. If any of the parent directories do not exist, they will be created as needed.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.create_directory\ :\ func(path:\ Path,\ permissions\ =\ Int32(0o755)\ ->\ Void)
.fi

.SH DESCRIPTION
Creates a new directory at the specified path with the given permissions. If any of the parent directories do not exist, they will be created as needed.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path of the directory to create. 	-
permissions		The permissions to set on the new directory. 	Int32(0o755)
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
(./new_directory).create_directory()
.EE
