'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH print 3 2025-11-09 "Tomo man-pages"
.SH NAME
print \- print some text
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI print\ :\ func(text:\ Text,\ newline:\ Bool\ =\ yes\ ->\ Void)
.fi
.SH DESCRIPTION
Prints a message to the console (alias for say()).


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
text	Text	The text to print. 	-
newline	Bool	Whether or not to print a newline after the text. 	yes
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
print("Hello ", newline=no)
print("world!")
.EE
