'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Table.set 3 2025-04-21T14:54:02.050025 "Tomo man-pages"
.SH NAME
Table.set \- set a table entry
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Table.set\ :\ func(t:\ {K=V},\ key:\ K,\ value:\ V\ ->\ Void)
.fi
.SH DESCRIPTION
Sets or updates the value associated with a specified key.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
t	{K=V}	The reference to the table. 	-
key	K	The key to set or update. 	-
value	V	The value to associate with the key. 	-
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
t := {"A"=1, "B"=2}
t.set("C", 3)
>> t
= {"A"=1, "B"=2, "C"=3}
.EE
