'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Text.utf32 3 2025-09-09 "Tomo man-pages"
.SH NAME
Text.utf32 \- get UTF32 codepoints
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Text.utf32\ :\ func(text:\ Text\ ->\ [Int32])
.fi
.SH DESCRIPTION
Returns a list of Unicode code points for UTF32 encoding of the text.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
text	Text	The text from which to extract Unicode code points. 	-
.TE
.SH RETURN
A list of 32-bit integer Unicode code points (`[Int32]`).

.SH EXAMPLES
.EX
>> "Amélie".utf32()
= [65, 109, 233, 108, 105, 101]
.EE
