'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.is_between 3 2026-08-27 "Tomo man-pages"
.SH NAME
Num.is_between \- range check
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.is_between\ :\ func(x:\ Num,\ low:\ Num,\ high:\ Num\ ->\ Bool)
.fi
.SH DESCRIPTION
Whether a number lies within a range, inclusive.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Num	The number to check. 
low	Num	The lower bound. 
high	Num	The upper bound. 
.TE
.SH RETURN
`yes` if `low <= x <= high`.

.SH EXAMPLES
.EX
assert (0.5).is_between(0, 1)
assert not (1.5).is_between(0, 1)
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
