'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH List.by 3 2025-04-19T14:30:40.360962 "Tomo man-pages"
.SH NAME
List.by \- Creates a new list with elements spaced by the specified step value.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI "List.by : func(list: [T], step: Int -> [T])"
.fi

.SH DESCRIPTION
Creates a new list with elements spaced by the specified step value.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
list	[T]	The original list. 	-
step	Int	The step value for selecting elements. 	-
.TE
.SH RETURN
A new list with every `step`-th element from the original list.

.SH EXAMPLES
.EX
>> [1, 2, 3, 4, 5, 6].by(2)
= [1, 3, 5]
.EE
