'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.write_unique 3 2026-09-01 "Tomo man-pages"
.SH NAME
Path.write_unique \- write to a uniquely named file
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.write_unique\ :\ func(path:\ Path,\ text:\ Text\ ->\ Path?)
.fi
.SH DESCRIPTION
Writes the given text to a unique file path based on the specified path. The file is created if it doesn't exist. This is useful for creating temporary files.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
path	Path	The base path for generating the unique file. This path must include the string \fBXXXXXX\fR in the file base name. 
text	Text	The text to write to the file. 
.TE
.SH RETURN
The path of the newly created unique file, or `none` if the file could not be created.

.SH EXAMPLES
.EX
# The created path has the XXXXXX replaced by random characters,
# e.g. (./file-27QHtq.txt):
created := (./file-XXXXXX.txt).write_unique("Hello, world!")!
assert created.read()! == "Hello, world!"
created.remove()!
.EE
.SH SEE ALSO
.BR Tomo-Path (3)
