'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Text.upper 3 2025-04-21T14:54:02.051669 "Tomo man-pages"
.SH NAME
Text.upper \- uppercase
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Text.upper\ :\ func(text:\ Text,\ language:\ Text\ =\ "C"\ ->\ Text)
.fi
.SH DESCRIPTION
Converts all characters in the text to uppercase.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
text	Text	The text to be converted to uppercase. 	-
language	Text	The ISO 639 language code for which casing rules to use. 	"C"
.TE
.SH RETURN
The uppercase version of the text.

.SH EXAMPLES
.EX
>> "amélie".upper()
= "AMÉLIE"

# In Turkish, uppercase "i" is "İ"
>> "i".upper(language="tr_TR")
= "İ"
.EE
