'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.accessed 3 2025-04-21T14:58:16.950040 "Tomo man-pages"
.SH NAME
Path.accessed \- access time
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.accessed\ :\ func(path:\ Path,\ follow_symlinks:\ Bool\ =\ yes\ ->\ Int64?)
.fi
.SH DESCRIPTION
Gets the file access time of a file.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path of the file whose access time you want. 	-
follow_symlinks	Bool	Whether to follow symbolic links. 	yes
.TE
.SH RETURN
A 64-bit unix epoch timestamp representing when the file or directory was last accessed, or `none` if no such file or directory exists.

.SH EXAMPLES
.EX
>> (./file.txt).accessed()
= 1704221100?
>> (./not-a-file).accessed()
= none
.EE
