'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.atanh 3 2025-04-21 "Tomo man-pages"
.SH NAME
Num.atanh \- arc hyperbolic tangent.
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.atanh\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the inverse hyperbolic tangent of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the inverse hyperbolic tangent is to be calculated. 	-
.TE
.SH RETURN
The inverse hyperbolic tangent of `x`.

.SH EXAMPLES
.EX
>> (0.5).atanh()
= 0.5493
.EE
