'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.j0 3 2025-11-09 "Tomo man-pages"
.SH NAME
Float64.j0 \- Bessel function
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.j0\ :\ func(x:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes the Bessel function of the first kind of order 0.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Float64	The number for which the Bessel function is to be calculated. 	-
.TE
.SH RETURN
The Bessel function of the first kind of order 0 of `x`.

.SH EXAMPLES
.EX
assert (0.0).j0() == 1
.EE
