'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.tgamma 3 2025-09-06 "Tomo man-pages"
.SH NAME
Num.tgamma \- true gamma function
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.tgamma\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the gamma function of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the gamma function is to be calculated. 	-
.TE
.SH RETURN
The gamma function of `x`.

.SH EXAMPLES
.EX
>> (1.0).tgamma()
= 1
.EE
