'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Int.clamped 3 2025-09-06 "Tomo man-pages"
.SH NAME
Int.clamped \- clamp an integer
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Int.clamped\ :\ func(x:\ Int,\ low:\ Int,\ high:\ Int\ ->\ Int)
.fi
.SH DESCRIPTION
Returns the given number clamped between two values so that it is within that range.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Int	The integer to clamp. 	-
low	Int	The lowest value the result can take. 	-
high	Int	The highest value the result can take. 	-
.TE
.SH RETURN
The first argument clamped between the other two arguments.

.SH EXAMPLES
.EX
>> (2).clamped(5, 10)
= 5
.EE
