'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.log2 3 2025-11-29 "Tomo man-pages"
.SH NAME
Num.log2 \- logarithm base-2
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.log2\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the base-2 logarithm of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the base-2 logarithm is to be calculated. 	-
.TE
.SH RETURN
The base-2 logarithm of `x`.

.SH EXAMPLES
.EX
assert (8.0).log2() == 3
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
