'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.copysign 3 2025-11-09 "Tomo man-pages"
.SH NAME
Float64.copysign \- copy a number's sign
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.copysign\ :\ func(x:\ Float64,\ y:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Copies the sign of one number to another.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Float64	The number whose magnitude will be copied. 	-
y	Float64	The number whose sign will be copied. 	-
.TE
.SH RETURN
A number with the magnitude of `x` and the sign of `y`.

.SH EXAMPLES
.EX
assert (3.0).copysign(-1) == -3
.EE
