'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.from_components 3 2025-11-09 "Tomo man-pages"
.SH NAME
Path.from_components \- build a path from components
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.from_components\ :\ func(components:\ [Text]\ ->\ Path)
.fi
.SH DESCRIPTION
Returns a path built from a list of path components.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
components	[Text]	A list of path components. 	-
.TE
.SH RETURN
A path representing the given components.

.SH EXAMPLES
.EX
assert Path.from_components(["/", "usr", "include"]) == (/usr/include)
assert Path.from_components(["foo.txt"]) == (./foo.txt)
assert Path.from_components(["~", ".local"]) == (~/.local)
.EE
