'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.is_socket 3 2026-09-01 "Tomo man-pages"
.SH NAME
Path.is_socket \- check if a path is a socket
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.is_socket\ :\ func(path:\ Path,\ follow_symlinks:\ Bool\ =\ yes\ ->\ Bool)
.fi
.SH DESCRIPTION
Checks if the path represents a socket. Optionally follows symbolic links.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path to check. 	-
follow_symlinks	Bool	Whether to follow symbolic links. 	yes
.TE
.SH RETURN
`yes` if the path is a socket, otherwise `no`.

.SH EXAMPLES
.EX
assert (./socket).is_socket()
.EE
.SH SEE ALSO
.BR Tomo-Path (3)
