'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.cos 3 2025-11-09 "Tomo man-pages"
.SH NAME
Float64.cos \- cosine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.cos\ :\ func(x:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes the cosine of a number (angle in radians).


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Float64	The angle in radians. 	-
.TE
.SH RETURN
The cosine of `x`.

.SH EXAMPLES
.EX
assert (0.0).cos() == 1
.EE
