'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Int.format 3 2025-04-19T14:30:40.360458 "Tomo man-pages"
.SH NAME
Int.format \- Formats an integer as a string with a specified number of digits.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI "Int.format : func(i: Int, digits: Int = 0 -> Text)"
.fi

.SH DESCRIPTION
Formats an integer as a string with a specified number of digits.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
i	Int	The integer to be formatted. 	-
digits	Int	The minimum number of digits to which the integer should be padded. 	0
.TE
.SH RETURN
A string representation of the integer, padded to the specified number of digits.

.SH EXAMPLES
.EX
>> (42).format(digits=5)
= "00042"
.EE
