'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.current_dir 3 2026-09-01 "Tomo man-pages"
.SH NAME
Path.current_dir \- get current directory
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.current_dir\ :\ func(->\ Path)
.fi
.SH DESCRIPTION
Returns the absolute path of the current working directory.


.SH RETURN
The absolute path of the current directory.

.SH EXAMPLES
.EX
assert Path.current_dir() == (/home/user/tomo)
.EE
.SH SEE ALSO
.BR Tomo-Path (3)
