'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.atan 3 2026-08-27 "Tomo man-pages"
.SH NAME
Num.atan \- arc tangent
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.atan\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
The arc tangent of a number, in radians. Defined for every number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Num	The number whose arc tangent is to be computed. 
.TE
.SH RETURN
The arc tangent of `x`.

.SH EXAMPLES
.EX
assert (0.).atan() == 0
assert (1.).atan() == Num.PI / 4
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
