'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.relative_to 3 2025-04-27 "Tomo man-pages"
.SH NAME
Path.relative_to \- apply a relative path to another
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.relative_to\ :\ func(path:\ Path,\ relative_to\ =\ (./)\ ->\ Path)
.fi
.SH DESCRIPTION
Returns the path relative to a given base path. By default, the base path is the current directory.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path to convert. 	-
relative_to		The base path for the relative path. 	(./)
.TE
.SH RETURN
The relative path.

.SH EXAMPLES
.EX
>> (./path/to/file.txt).relative(relative_to=(./path))
= (./to/file.txt)
.EE
