'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Text.split_any 3 2025-04-19T14:30:40.368129 "Tomo man-pages"
.SH NAME
Text.split_any \- Splits the text into a list of substrings at one or more occurrences of a set of delimiter characters (grapheme clusters). **Note:** to split based on an exact delimiter, use [`split()`](#split).

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI "Text.split_any : func(text: Text, delimiters: Text = " $\\t\\r\\n" -> [Text])"
.fi

.SH DESCRIPTION
Splits the text into a list of substrings at one or more occurrences of a set of delimiter characters (grapheme clusters). **Note:** to split based on an exact delimiter, use [`split()`](#split).


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
text	Text	The text to be split. 	-
delimiters	Text	A text containing multiple delimiters to be used for  splitting the text into chunks. 	" $\\t\\r\\n"
.TE
.SH RETURN
A list of subtexts resulting from the split.

.SH EXAMPLES
.EX
>> "one, two,,three".split_any(", ")
= ["one", "two", "three"]
.EE
