'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.cosh 3 2025-04-30 "Tomo man-pages"
.SH NAME
Num.cosh \- hyperbolic cosine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.cosh\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the hyperbolic cosine of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the hyperbolic cosine is to be calculated. 	-
.TE
.SH RETURN
The hyperbolic cosine of `x`.

.SH EXAMPLES
.EX
>> (0.0).cosh()
= 1
.EE
