'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH fail 3 2025-11-29 "Tomo man-pages"
.SH NAME
fail \- abort the program
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI fail\ :\ func(message:\ Text\ ->\ Abort)
.fi
.SH DESCRIPTION
Prints a message to the console, aborts the program, and prints a stack trace.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
message	Text	The error message to print. 
.TE
.SH RETURN
Nothing, aborts the program.

.SH EXAMPLES
.EX
fail("Oh no!")
.EE
