'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.ceil 3 2026-08-27 "Tomo man-pages"
.SH NAME
Num.ceil \- round up
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.ceil\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
The smallest whole number greater than or equal to a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Num	The number to round up. 
.TE
.SH RETURN
`x` rounded up.

.SH EXAMPLES
.EX
assert (4.2).ceil() == 5
assert (-4.2).ceil() == -4
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
