'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.sibling 3 2025-11-09 "Tomo man-pages"
.SH NAME
Path.sibling \- get another path in the same directory
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.sibling\ :\ func(path:\ Path,\ name:\ Text\ ->\ Path)
.fi
.SH DESCRIPTION
Return a path that is a sibling of another path (i.e. has the same parent, but a different name). This is equivalent to `.parent().child(name)`


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	A path. 	-
name	Text	The name of a sibling file or directory. 	-
.TE
.SH RETURN
A new path representing the sibling.

.SH EXAMPLES
.EX
assert (/foo/baz).sibling("doop") == (/foo/doop)
.EE
