'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Text.codepoint_names 3 2025-11-29 "Tomo man-pages"
.SH NAME
Text.codepoint_names \- get unicode codepoint names
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Text.codepoint_names\ :\ func(text:\ Text\ ->\ [Text])
.fi
.SH DESCRIPTION
Returns a list of the names of each codepoint in the text.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
text	Text	The text from which to extract codepoint names. 
.TE
.SH RETURN
A list of codepoint names (`[Text]`).

.SH EXAMPLES
.EX
assert "Amélie".codepoint_names() == [
    "LATIN CAPITAL LETTER A",
    "LATIN SMALL LETTER M",
    "LATIN SMALL LETTER E WITH ACUTE",
    "LATIN SMALL LETTER L",
    "LATIN SMALL LETTER I",
    "LATIN SMALL LETTER E",
]
.EE
.SH SEE ALSO
.BR Tomo-Text (3)
