'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Int.is_between 3 2025-11-29 "Tomo man-pages"
.SH NAME
Int.is_between \- test if an int is in a range
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Int.is_between\ :\ func(x:\ Int,\ low:\ Int,\ high:\ Int\ ->\ Bool)
.fi
.SH DESCRIPTION
Determines if an integer is between two numbers (inclusive).


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Int	The integer to be checked. 
low	Int	The lower bound to check (inclusive). 
high	Int	The upper bound to check (inclusive). 
.TE
.SH RETURN
`yes` if `low <= x and x <= high`, otherwise `no`

.SH EXAMPLES
.EX
assert (7).is_between(1, 10) == yes
assert (7).is_between(100, 200) == no
assert (7).is_between(1, 7) == yes
.EE
.SH SEE ALSO
.BR Tomo-Int (3)
