'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.log10 3 2025-09-06 "Tomo man-pages"
.SH NAME
Num.log10 \- logarithm base-10
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.log10\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the base-10 logarithm of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the base-10 logarithm is to be calculated. 	-
.TE
.SH RETURN
The base-10 logarithm of `x`.

.SH EXAMPLES
.EX
>> (100.0).log10()
= 2
.EE
