'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.exp 3 2026-03-08 "Tomo man-pages"
.SH NAME
Num.exp \- base-e exponentiation
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.exp\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the exponential function $e^x$ for a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Num	The exponent. 
.TE
.SH RETURN
The value of $e^x$.

.SH EXAMPLES
.EX
assert (1.0).exp().near(2.718281828459045)
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
