'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.subdirectories 3 2025-09-21 "Tomo man-pages"
.SH NAME
Path.subdirectories \- get subdirectories
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.subdirectories\ :\ func(path:\ Path,\ include_hidden\ =\ no\ ->\ [Path])
.fi
.SH DESCRIPTION
Returns a list of subdirectories within the directory at the specified path. Optionally includes hidden subdirectories.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path of the directory. 	-
include_hidden		Whether to include hidden subdirectories. 	no
.TE
.SH RETURN
A list of subdirectory paths.

.SH EXAMPLES
.EX
assert (./directory).subdirectories() == [(./directory/subdir1), (./directory/subdir2)]
assert (./directory).subdirectories(include_hidden=yes) == [(./directory/.git), (./directory/subdir1), (./directory/subdir2)]
.EE
