'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.rint 3 2025-04-19T14:30:40.363539 "Tomo man-pages"
.SH NAME
Num.rint \- Rounds a number to the nearest integer, with ties rounded to the nearest even integer.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI "Num.rint : func(x: Num -> Num)"
.fi

.SH DESCRIPTION
Rounds a number to the nearest integer, with ties rounded to the nearest even integer.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number to be rounded. 	-
.TE
.SH RETURN
The nearest integer value of `x`.

.SH EXAMPLES
.EX
>> (3.5).rint()
= 4
>> (2.5).rint()
= 2
.EE
