'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float.trunc 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float.trunc \- truncate a number
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float.trunc\ :\ func(x:\ Float\ ->\ Float)
.fi
.SH DESCRIPTION
Truncates a number to the nearest integer towards zero.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float	The number to be truncated. 
.TE
.SH RETURN
The integer part of `x` towards zero.

.SH EXAMPLES
.EX
assert (3.7).trunc() == 3
assert (-3.7).trunc() == -3
.EE
.SH SEE ALSO
.BR Tomo-Float (3)
