'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Set.clear 3 2025-04-21T14:54:02.049450 "Tomo man-pages"
.SH NAME
Set.clear \- clear a set
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Set.clear\ :\ func(set:\ @|T|\ ->\ Void)
.fi
.SH DESCRIPTION
Removes all items from the set.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
set	@|T|	The mutable reference to the set. 	-
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
>> nums.clear()
.EE
