'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.j1 3 2025-04-19T14:52:07.135605 "Tomo man-pages"
.SH NAME
Num.j1 \- Computes the Bessel function of the first kind of order 1.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.j1\ :\ func(x:\ Num\ ->\ Num)
.fi

.SH DESCRIPTION
Computes the Bessel function of the first kind of order 1.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the Bessel function is to be calculated. 	-
.TE
.SH RETURN
The Bessel function of the first kind of order 1 of `x`.

.SH EXAMPLES
.EX
>> (0.0).j1()
= 0
.EE
