'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Set.is_subset_of 3 2025-04-19T14:52:07.138911 "Tomo man-pages"
.SH NAME
Set.is_subset_of \- Checks if the set is a subset of another set.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Set.is_subset_of\ :\ func(set:\ |T|,\ other:\ |T|,\ strict:\ Bool\ =\ no\ ->\ Bool)
.fi

.SH DESCRIPTION
Checks if the set is a subset of another set.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
set	|T|	The set to check. 	-
other	|T|	The set to compare against. 	-
strict	Bool	If `yes`, checks if the set is a strict subset (does not equal the other set). 	no
.TE
.SH RETURN
`yes` if the set is a subset of the other set (strictly or not), `no` otherwise.

.SH EXAMPLES
.EX
>> |1, 2|.is_subset_of(|1, 2, 3|)
= yes
.EE
