'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.cbrt 3 2025-04-21T14:58:16.947655 "Tomo man-pages"
.SH NAME
Num.cbrt \- cube root
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.cbrt\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the cube root of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the cube root is to be calculated. 	-
.TE
.SH RETURN
The cube root of `x`.

.SH EXAMPLES
.EX
>> (27.0).cbrt()
= 3
.EE
