'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH CString 3 2026-09-01 "Tomo man-pages"
.SH NAME
CString \- a Tomo type
.SH LIBRARY
Tomo Standard Library
.fi
.SH METHODS

.TP
.BI CString.as_text\ :\ func(str:\ CString\ ->\ Text?)
Convert a C string to Text. This is the same conversion that \fBText(str)\fR performs. 

For more, see:
.BR Tomo-CString.as_text (3)


.TP
.BI CString.bytes\ :\ func(str:\ CString\ ->\ [Byte])
Convert a C string to a list of its raw bytes. 

For more, see:
.BR Tomo-CString.bytes (3)


.TP
.BI CString.join\ :\ func(glue:\ CString,\ pieces:\ [CString]\ ->\ CString)
Join a list of C strings together with a separator. 

For more, see:
.BR Tomo-CString.join (3)

