'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.has_extension 3 2025-06-24 "Tomo man-pages"
.SH NAME
Path.has_extension \- check if a path has a given extension
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.has_extension\ :\ func(path:\ Path,\ extension:\ Text\ ->\ Bool)
.fi
.SH DESCRIPTION
Return whether or not a path has a given file extension.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	A path. 	-
extension	Text	A file extension (leading `.` is optional). If empty, the check will test if the file does not have any file extension. 	-
.TE
.SH RETURN
Whether or not the path has the given extension.

.SH EXAMPLES
.EX
>> (/foo.txt).has_extension("txt")
= yes
>> (/foo.txt).has_extension(".txt")
= yes
>> (/foo.tar.gz).has_extension("gz")
= yes
>> (/foo.tar.gz).has_extension("zip")
= no
.EE
