'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float.2_SQRTPI 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float.2_SQRTPI \- 2*sqrt(pi)
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float.2_SQRTPI\ :\ Float
.fi
.SH DESCRIPTION
The constant $2 \times \sqrt{\pi}$.


.SH SEE ALSO
.BR Tomo-Float (3)
