'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Set.without 3 2025-04-19T14:52:07.139141 "Tomo man-pages"
.SH NAME
Set.without \- Creates a new set with items from the original set but without items from another set.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Set.without\ :\ func(set:\ |T|,\ other:\ |T|\ ->\ |T|)
.fi

.SH DESCRIPTION
Creates a new set with items from the original set but without items from another set.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
set	|T|	The original set. 	-
other	|T|	The set of items to remove from the original set. 	-
.TE
.SH RETURN
A new set containing items from the original set excluding those in the other set.

.SH EXAMPLES
.EX
>> |1, 2|.without(|2, 3|)
= |1|
.EE
