'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float.parse 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float.parse \- convert text to number
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float.parse\ :\ func(text:\ Text,\ remainder:\ &Text?\ =\ none\ ->\ Float?)
.fi
.SH DESCRIPTION
Converts a text representation of a number into a floating-point number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
text	Text	The text containing the number. 	-
remainder	&Text?	If non-none, this argument will be set to the remainder of the text after the matching part. If none, parsing will only succeed if the entire text matches. 	none
.TE
.SH RETURN
The number represented by the text or `none` if the entire text can't be parsed as a number.

.SH EXAMPLES
.EX
assert Float.parse("3.14") == 3.14
assert Float.parse("1e3") == 1000
assert Float.parse("1.5junk") == none
remainder : Text
assert Float.parse("1.5junk", &remainder) == 1.5
assert remainder == "junk"
.EE
.SH SEE ALSO
.BR Tomo-Float (3)
