'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.append 3 2025-04-27 "Tomo man-pages"
.SH NAME
Path.append \- append to a file
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.append\ :\ func(path:\ Path,\ text:\ Text,\ permissions:\ Int32\ =\ Int32(0o644)\ ->\ Void)
.fi
.SH DESCRIPTION
Appends the given text to the file at the specified path, creating the file if it doesn't already exist. Failure to write will result in a runtime error.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path of the file to append to. 	-
text	Text	The text to append to the file. 	-
permissions	Int32	The permissions to set on the file if it is being created. 	Int32(0o644)
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
(./log.txt).append("extra line$(\[rs]n)")
.EE
