'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH List.shuffle 3 2025-04-21T14:54:02.045319 "Tomo man-pages"
.SH NAME
List.shuffle \- shuffle a list in place
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI List.shuffle\ :\ func(list:\ @[T],\ random:\ func(min,max:Int64->Int64)?\ =\ none\ ->\ Void)
.fi
.SH DESCRIPTION
Shuffles the elements of the list in place.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
list	@[T]	The mutable reference to the list to be shuffled. 	-
random	func(min,max:Int64->Int64)?	If provided, this function will be used to get a random index in the list. Returned values must be between `min` and `max` (inclusive). (Used for deterministic pseudorandom number generation) 	none
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
>> list.shuffle()
.EE
