'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float.significand 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float.significand \- get mantissa
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float.significand\ :\ func(x:\ Float\ ->\ Float)
.fi
.SH DESCRIPTION
Extracts the significand (or mantissa) of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float	The number from which to extract the significand. 
.TE
.SH RETURN
The significand of `x`.

.SH EXAMPLES
.EX
assert (1234.567).significand() == 0.1234567
.EE
.SH SEE ALSO
.BR Tomo-Float (3)
