'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Set.overlap 3 2025-04-21 "Tomo man-pages"
.SH NAME
Set.overlap \- set intersection
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Set.overlap\ :\ func(set:\ |T|,\ other:\ |T|\ ->\ |T|)
.fi
.SH DESCRIPTION
Creates a new set with items that are in both the original set and another set.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
set	|T|	The original set. 	-
other	|T|	The set to intersect with. 	-
.TE
.SH RETURN
A new set containing only items present in both sets.

.SH EXAMPLES
.EX
>> |1, 2|.overlap(|2, 3|)
= |2|
.EE
