'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Text.left_pad 3 2025-11-09 "Tomo man-pages"
.SH NAME
Text.left_pad \- left-pad text
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Text.left_pad\ :\ func(text:\ Text,\ width:\ Int,\ pad:\ Text\ =\ "\ ",\ language:\ Text\ =\ "C"\ ->\ Text)
.fi
.SH DESCRIPTION
Pad some text on the left side so it reaches a target width.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
text	Text	The text to pad. 	-
width	Int	The target width. 	-
pad	Text	The padding text. 	"\ "
language	Text	The ISO 639 language code for which character width to use. 	"C"
.TE
.SH RETURN
Text with length at least `width`, with extra padding on the left as needed. If `pad` has length greater than 1, it may be partially repeated to reach the exact desired length.

.SH EXAMPLES
.EX
assert "x".left_pad(5) == "    x"
assert "x".left_pad(5, "ABC") == "ABCAx"
.EE
