'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.child 3 2025-11-29 "Tomo man-pages"
.SH NAME
Path.child \- append a child to a path
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.child\ :\ func(path:\ Path,\ child:\ Text\ ->\ Path)
.fi
.SH DESCRIPTION
Return a path that is a child of another path.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
path	Path	The path of a directory. 
child	Text	The name of a child file or directory. 
.TE
.SH RETURN
A new path representing the child.

.SH EXAMPLES
.EX
assert (./directory).child("file.txt") == (./directory/file.txt)
.EE
.SH SEE ALSO
.BR Tomo-Path (3)
