'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float.isfinite 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float.isfinite \- check for finite number
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float.isfinite\ :\ func(n:\ Float\ ->\ Bool)
.fi
.SH DESCRIPTION
Checks if a number is finite.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
n	Float	The number to be checked. 
.TE
.SH RETURN
`yes` if `n` is finite, `no` otherwise.

.SH EXAMPLES
.EX
assert (1.0).isfinite() == yes
assert Float.INF.isfinite() == no
.EE
.SH SEE ALSO
.BR Tomo-Float (3)
