'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Table.xor 3 2025-06-24 "Tomo man-pages"
.SH NAME
Table.xor \- symmetric difference
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Table.xor\ :\ func(a:\ |T|,\ b:\ |T|\ ->\ |T|)
.fi
.SH DESCRIPTION
Return set with the elements in one, but not both of the arguments. This is also known as the symmetric difference or disjunctive union.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
a	|T|	The first set. 	-
b	|T|	The second set. 	-
.TE
.SH RETURN
A set with the symmetric difference of the arguments.

.SH EXAMPLES
.EX
>> |1, 2, 3|.xor(|2, 3, 4|)
= |1, 4|
.EE
