'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.max 3 2026-08-27 "Tomo man-pages"
.SH NAME
Num.max \- larger of two numbers
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.max\ :\ func(x:\ Num,\ y:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
The larger of two numbers.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Num	The first number. 
y	Num	The second number. 
.TE
.SH RETURN
Whichever of `x` and `y` is larger.

.SH EXAMPLES
.EX
assert (0.3).max(0.5) == 0.5
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
