'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH List.to 3 2025-11-29 "Tomo man-pages"
.SH NAME
List.to \- slice a list to an end index
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI List.to\ :\ func(list:\ [T],\ last:\ Int\ ->\ [T])
.fi
.SH DESCRIPTION
Returns a slice of the list from the start of the original list up to a specified index (inclusive).


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
list	[T]	The original list. 
last	Int	The index up to which elements should be included. 
.TE
.SH RETURN
A new list containing elements from the start up to the specified index.

.SH EXAMPLES
.EX
assert [10, 20, 30, 40, 50].to(3) == [10, 20, 30]
assert [10, 20, 30, 40, 50].to(-2) == [10, 20, 30, 40]
.EE
.SH SEE ALSO
.BR Tomo-List (3)
