'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.tgamma 3 2025-11-09 "Tomo man-pages"
.SH NAME
Float64.tgamma \- true gamma function
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.tgamma\ :\ func(x:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes the gamma function of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Float64	The number for which the gamma function is to be calculated. 	-
.TE
.SH RETURN
The gamma function of `x`.

.SH EXAMPLES
.EX
assert (1.0).tgamma() == 1
.EE
