'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.INF 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float64.INF \- infinity
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.INF\ :\ Float64
.fi
.SH DESCRIPTION
Positive infinity.


.SH SEE ALSO
.BR Tomo-Float64 (3)
