'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.floor 3 2025-04-21T14:54:02.046332 "Tomo man-pages"
.SH NAME
Num.floor \- floor function
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.floor\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Rounds a number down to the nearest integer.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number to be rounded down. 	-
.TE
.SH RETURN
The largest integer less than or equal to `x`.

.SH EXAMPLES
.EX
>> (3.7).floor()
= 3
.EE
