'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.nextafter 3 2025-11-09 "Tomo man-pages"
.SH NAME
Float64.nextafter \- next floating point number
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.nextafter\ :\ func(x:\ Float64,\ y:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes the next representable value after a given number towards a specified direction.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Float64	The starting number. 	-
y	Float64	The direction towards which to find the next representable value. 	-
.TE
.SH RETURN
The next representable value after `x` in the direction of `y`.

.SH EXAMPLES
.EX
assert (1.0).nextafter(1.1) == 1.0000000000000002
.EE
