'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.append_bytes 3 2025-04-19T14:48:15.714592 "Tomo man-pages"
.SH NAME
Path.append_bytes \- Appends the given bytes to the file at the specified path, creating the file if it doesn't already exist. Failure to write will result in a runtime error.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.append_bytes\ :\ func(path:\ Path,\ bytes:\ [Byte],\ permissions:\ Int32\ =\ Int32(0o644)\ ->\ Void)
.fi

.SH DESCRIPTION
Appends the given bytes to the file at the specified path, creating the file if it doesn't already exist. Failure to write will result in a runtime error.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path of the file to append to. 	-
bytes	[Byte]	The bytes to append to the file. 	-
permissions	Int32	The permissions to set on the file if it is being created. 	Int32(0o644)
.TE
.SH RETURN
Nothing.

.SH EXAMPLES
.EX
(./log.txt).append_bytes([104, 105])
.EE
