'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.E 3 2025-04-19T14:52:07.136808 "Tomo man-pages"
.SH NAME
Num.E \- The base of the natural logarithm ($e$).

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.E\ :\ Num
.fi

.SH DESCRIPTION
The base of the natural logarithm ($e$).

