'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.abs 3 2026-08-27 "Tomo man-pages"
.SH NAME
Num.abs \- absolute value
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.abs\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
The absolute value of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Num	The number whose absolute value is to be computed. 
.TE
.SH RETURN
The absolute value of `x`.

.SH EXAMPLES
.EX
assert (-3.5).abs() == 3.5
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
