'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.sqrt 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float64.sqrt \- square root
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.sqrt\ :\ func(x:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes the square root of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float64	The number for which the square root is to be calculated. 
.TE
.SH RETURN
The square root of `x`.

.SH EXAMPLES
.EX
assert (16.0).sqrt() == 4
.EE
.SH SEE ALSO
.BR Tomo-Float64 (3)
