'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float.sinh 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float.sinh \- hyperbolic sine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float.sinh\ :\ func(x:\ Float\ ->\ Float)
.fi
.SH DESCRIPTION
Computes the hyperbolic sine of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float	The number for which the hyperbolic sine is to be calculated. 
.TE
.SH RETURN
The hyperbolic sine of `x`.

.SH EXAMPLES
.EX
assert (0.0).sinh() == 0
.EE
.SH SEE ALSO
.BR Tomo-Float (3)
