'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.can_write 3 2025-11-29 "Tomo man-pages"
.SH NAME
Path.can_write \- check write permissions
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.can_write\ :\ func(path:\ Path\ ->\ Bool)
.fi
.SH DESCRIPTION
Returns whether or not a file can be written by the current user/group.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
path	Path	The path of the file to check. 
.TE
.SH RETURN
`yes` if the file or directory exists and the current user has write permissions, otherwise `no`.

.SH EXAMPLES
.EX
assert (/tmp).can_write() == yes
assert (/etc/passwd).can_write() == no
assert (/non/existant/file).can_write() == no
.EE
.SH SEE ALSO
.BR Tomo-Path (3)
