'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.atan2 3 2025-09-21 "Tomo man-pages"
.SH NAME
Num.atan2 \- arc tangent from 2 variables
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.atan2\ :\ func(x:\ Num,\ y:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the arc tangent of the quotient of two numbers.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The numerator. 	-
y	Num	The denominator. 	-
.TE
.SH RETURN
The arc tangent of `x/y` in radians.

.SH EXAMPLES
.EX
assert Num.atan2(1, 1) == 0.7854
.EE
