'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.2_SQRTPI 3 2025-11-09 "Tomo man-pages"
.SH NAME
Float64.2_SQRTPI \- 2*sqrt(pi)
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.2_SQRTPI\ :\ Float64
.fi
.SH DESCRIPTION
The constant $2 \times \sqrt{\pi}$.


