'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.children 3 2025-04-19T14:48:15.714904 "Tomo man-pages"
.SH NAME
Path.children \- Returns a list of children (files and directories) within the directory at the specified path. Optionally includes hidden files.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.children\ :\ func(path:\ Path,\ include_hidden\ =\ no\ ->\ [Path])
.fi

.SH DESCRIPTION
Returns a list of children (files and directories) within the directory at the specified path. Optionally includes hidden files.


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path of the directory. 	-
include_hidden		Whether to include hidden files, which start with a `.`. 	no
.TE
.SH RETURN
A list of paths for the children.

.SH EXAMPLES
.EX
>> (./directory).children(include_hidden=yes)
= [".git", "foo.txt"]
.EE
