'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.is_pipe 3 2026-09-01 "Tomo man-pages"
.SH NAME
Path.is_pipe \- check if a path is a named pipe
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.is_pipe\ :\ func(path:\ Path,\ follow_symlinks:\ Bool\ =\ yes\ ->\ Bool)
.fi
.SH DESCRIPTION
Checks if the path represents a named pipe (a FIFO). Optionally follows symbolic links.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path to check. 	-
follow_symlinks	Bool	Whether to follow symbolic links. 	yes
.TE
.SH RETURN
`yes` if the path is a named pipe, otherwise `no`.

.SH EXAMPLES
.EX
assert (./my-fifo).is_pipe()
assert not (./file.txt).is_pipe()
.EE
.SH SEE ALSO
.BR Tomo-Path (3)
