'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.tan 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float64.tan \- tangent
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.tan\ :\ func(x:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes the tangent of a number (angle in radians).


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float64	The angle in radians. 
.TE
.SH RETURN
The tangent of `x`.

.SH EXAMPLES
.EX
assert (0.0).tan() == 0
.EE
.SH SEE ALSO
.BR Tomo-Float64 (3)
