'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.hypot 3 2025-04-21T14:54:02.046397 "Tomo man-pages"
.SH NAME
Num.hypot \- Euclidean distance function
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.hypot\ :\ func(x:\ Num,\ y:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the Euclidean norm, $\sqrt{x^2 + y^2}$, of two numbers.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The first number. 	-
y	Num	The second number. 	-
.TE
.SH RETURN
The Euclidean norm of `x` and `y`.

.SH EXAMPLES
.EX
>> Num.hypot(3, 4)
= 5
.EE
