'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.log2 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float64.log2 \- logarithm base-2
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.log2\ :\ func(x:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes the base-2 logarithm of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float64	The number for which the base-2 logarithm is to be calculated. 
.TE
.SH RETURN
The base-2 logarithm of `x`.

.SH EXAMPLES
.EX
assert (8.0).log2() == 3
.EE
.SH SEE ALSO
.BR Tomo-Float64 (3)
