'\" t
.\" Copyright (c) 2026 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.trunc 3 2026-08-27 "Tomo man-pages"
.SH NAME
Num.trunc \- round toward zero
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.trunc\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
The whole part of a number, discarding the fraction.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Num	The number to truncate. 
.TE
.SH RETURN
`x` with its fractional part removed.

.SH EXAMPLES
.EX
assert (4.8).trunc() == 4
assert (-4.8).trunc() == -4
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
