'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Table.get 3 2025-04-21T14:58:16.951992 "Tomo man-pages"
.SH NAME
Table.get \- get an item from a table
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Table.get\ :\ func(t:\ {K=V},\ key:\ K\ ->\ V?)
.fi
.SH DESCRIPTION
Retrieves the value associated with a key, or returns `none` if the key is not present.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
t	{K=V}	The table. 	-
key	K	The key whose associated value is to be retrieved. 	-
.TE
.SH RETURN
The value associated with the key or `none` if the key is not found.

.SH NOTES
Default values for the table are ignored.

.SH EXAMPLES
.EX
>> t := {"A"=1, "B"=2}
>> t.get("A")
= 1?

>> t.get("????")
= none

>> t.get("A")!
= 1

>> t.get("????") or 0
= 0
.EE
