'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.acos 3 2025-11-09 "Tomo man-pages"
.SH NAME
Float64.acos \- arc cosine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.acos\ :\ func(x:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes the arc cosine of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Float64	The number for which the arc cosine is to be calculated. 	-
.TE
.SH RETURN
The arc cosine of `x` in radians.

.SH EXAMPLES
.EX
assert (0.0).acos() == 1.5708
.EE
