'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.LN10 3 2025-04-19T14:30:40.364415 "Tomo man-pages"
.SH NAME
Num.LN10 \- The natural logarithm of 10.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI 'Num.LN10 : Num'
.fi

.SH DESCRIPTION
The natural logarithm of 10.

