'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.acosh 3 2025-11-09 "Tomo man-pages"
.SH NAME
Float64.acosh \- arc hyperbolic cosine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.acosh\ :\ func(x:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes the inverse hyperbolic cosine of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Float64	The number for which the inverse hyperbolic cosine is to be calculated. 	-
.TE
.SH RETURN
The inverse hyperbolic cosine of `x`.

.SH EXAMPLES
.EX
assert (1.0).acosh() == 0
.EE
