'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH List.unique 3 2025-04-30 "Tomo man-pages"
.SH NAME
List.unique \- convert a list to a set
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI List.unique\ :\ func(list:\ [T]\ ->\ |T|)
.fi
.SH DESCRIPTION
Returns a Set that contains the unique elements of the list.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
list	[T]	The list to process. 	-
.TE
.SH RETURN
A set containing only unique elements from the list.

.SH EXAMPLES
.EX
>> [10, 20, 10, 10, 30].unique()
= {10, 20, 30}
.EE
