'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float64.exp 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float64.exp \- base-e exponentiation
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float64.exp\ :\ func(x:\ Float64\ ->\ Float64)
.fi
.SH DESCRIPTION
Computes the exponential function $e^x$ for a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float64	The exponent. 
.TE
.SH RETURN
The value of $e^x$.

.SH EXAMPLES
.EX
assert (1.0).exp() == 2.7183
.EE
.SH SEE ALSO
.BR Tomo-Float64 (3)
