'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.is_between 3 2025-04-21T14:44:34.260375 "Tomo man-pages"
.SH NAME
Num.is_between \- check if a number is in a range
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.is_between\ :\ func(x:\ Num,\ low:\ Num,\ high:\ Num\ ->\ Bool)
.fi
.SH DESCRIPTION
Determines if a number is between two numbers (inclusive).


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The integer to be checked. 	-
low	Num	The lower bound to check (inclusive). 	-
high	Num	The upper bound to check (inclusive). 	-
.TE
.SH RETURN
`yes` if `low <= x and x <= high`, otherwise `no`

.SH EXAMPLES
.EX
>> (7.5).is_between(1, 10)
= yes
>> (7.5).is_between(100, 200)
= no
>> (7.5).is_between(1, 7.5)
= yes
.EE
