'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH USE_COLOR 3 2025-04-19T14:48:15.710142 "Tomo man-pages"
.SH NAME
USE_COLOR \- Whether or not the console prefers ANSI color escape sequences in the output.

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI USE_COLOR\ :\ Bool
.fi

.SH DESCRIPTION
Whether or not the console prefers ANSI color escape sequences in the output.

