'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.asin 3 2025-11-29 "Tomo man-pages"
.SH NAME
Num.asin \- arc sine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.asin\ :\ func(x:\ Num\ ->\ Num)
.fi
.SH DESCRIPTION
Computes the arc sine of a number.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The number for which the arc sine is to be calculated. 	-
.TE
.SH RETURN
The arc sine of `x` in radians.

.SH EXAMPLES
.EX
assert (0.5).asin() == 0.5236
.EE
.SH SEE ALSO
.BR Tomo-Num (3)
