'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Num.tan 3 2025-04-19T14:48:15.713796 "Tomo man-pages"
.SH NAME
Num.tan \- Computes the tangent of a number (angle in radians).

.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Num.tan\ :\ func(x:\ Num\ ->\ Num)
.fi

.SH DESCRIPTION
Computes the tangent of a number (angle in radians).


.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
x	Num	The angle in radians. 	-
.TE
.SH RETURN
The tangent of `x`.

.SH EXAMPLES
.EX
>> (0.0).tan()
= 0
.EE
