'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Path.is_socket 3 2025-04-21 "Tomo man-pages"
.SH NAME
Path.is_socket \- check if a path is a socket
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Path.is_socket\ :\ func(path:\ Path,\ follow_symlinks\ =\ yes\ ->\ Bool)
.fi
.SH DESCRIPTION
Checks if the path represents a socket. Optionally follows symbolic links.


.SH ARGUMENTS

.TS
allbox;
lb lb lbx lb
l l l l.
Name	Type	Description	Default
path	Path	The path to check. 	-
follow_symlinks		Whether to follow symbolic links. 	yes
.TE
.SH RETURN
`True` if the path is a socket, `False` otherwise.

.SH EXAMPLES
.EX
>> (./socket).is_socket()
= yes
.EE
