'\" t
.\" Copyright (c) 2025 Bruce Hill
.\" All rights reserved.
.\"
.TH Float.cos 3 2025-12-11 "Tomo man-pages"
.SH NAME
Float.cos \- cosine
.SH LIBRARY
Tomo Standard Library
.SH SYNOPSIS
.nf
.BI Float.cos\ :\ func(x:\ Float\ ->\ Float)
.fi
.SH DESCRIPTION
Computes the cosine of a number (angle in radians).


.SH ARGUMENTS

.TS
allbox;
lb lb lbx
l l l.
Name	Type	Description
x	Float	The angle in radians. 
.TE
.SH RETURN
The cosine of `x`.

.SH EXAMPLES
.EX
assert (0.0).cos() == 1
.EE
.SH SEE ALSO
.BR Tomo-Float (3)
